[project]
name = "game"
version = "0.1.0"
description = "The purpose of this project is to learn OOP by creating a game using Pygame"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame==2.6.1",
]
